default_context:
  project_name: 'video-storage'
  project_slug: 'video-storage'
  domain_main: 'video-storage.com'
  domain_staging: 'stag.video-storage.com'
  docker_swarm_stack_name_main: 'video-storage-com'
  docker_swarm_stack_name_staging: 'stag-video-storage-com'
  secret_key: 'f7f4dad96d5796c138164458516d1db8522dde3f8bbf35c8c74d947b1fd0faa4'
  first_superuser: 'admin@video-storage.com'
  first_superuser_password: '61087edc440ad5bc2438d7ad3668c87a7fced4a232a0a448a093c2f9c317833c'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.video-storage.com", "https://stag.video-storage.com", "https://video-storage.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@video-storage.com'
  postgres_password: 'b60b29b4077e8df112966892601dbe9f26dec4b0ba2ad232d852e213c9ae1473'
  pgadmin_default_user: 'admin@video-storage.com'
  pgadmin_default_user_password: '61087edc440ad5bc2438d7ad3668c87a7fced4a232a0a448a093c2f9c317833c'
  traefik_constraint_tag: 'video-storage.com'
  traefik_constraint_tag_staging: 'stag.video-storage.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:61087edc440ad5bc2438d7ad3668c87a7fced4a232a0a448a093c2f9c317833c'
  sentry_dsn: ''
  docker_image_prefix: 'video-storage'
  docker_image_backend: 'video-storage-backend'
  docker_image_celeryworker: 'video-storage-celeryworker'
  docker_image_frontend: 'video-storage-frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
